[meta]
version = 1
date = "2026-08-25"

[[screen]]
id = "s-eight-z2"
gadgets = 8
modulus = 2

[[screen]]
id = "s-twelve-z3"
gadgets = 12
modulus = 3

[[confirm]]
id = "c-ten-z5"
gadgets = 10
modulus = 5

[[confirm]]
id = "c-sixteen-z3"
gadgets = 16
modulus = 3

[[confirm]]
id = "c-twenty-z2"
gadgets = 20
modulus = 2
