[meta]
version = 1
date = "2026-08-25"

[[screen]]
id = "s-h1-z2"
dimension = 1
modulus = 2

[[screen]]
id = "s-h2-z3"
dimension = 2
modulus = 3

[[confirm]]
id = "c-h1-z5"
dimension = 1
modulus = 5

[[confirm]]
id = "c-h2-z2"
dimension = 2
modulus = 2

[[confirm]]
id = "c-h3-z5"
dimension = 3
modulus = 5
