[meta]
version = 1
date = "2026-08-25"

[[screen]]
id = "s-petals-24-z2"
petals = 24
modulus = 2

[[screen]]
id = "s-petals-40-z3"
petals = 40
modulus = 3

[[confirm]]
id = "c-petals-48-z5"
petals = 48
modulus = 5

[[confirm]]
id = "c-petals-72-z3"
petals = 72
modulus = 3

[[confirm]]
id = "c-petals-96-z2"
petals = 96
modulus = 2
